### ISSUE TITLE
GPG Signature Support

### ISSUE THREAD

**Issue by OuOich** [LogicOverSnacks/glint-release#14]
I really like this software because its UI is genuinely beautiful and it offers good localization support. Therefore, I subscribed to the premium version to support your development.

However, I’ve encountered a significant issue during use—it doesn’t support submitting with GPG signatures.

It would be fantastic if you could implement this feature, as I consider signature submission a crucial feature of Git. Otherwise, at present, I can only use it as a "commit browser."

**Comment by MikeJerred** [comment]
Glad you are enjoying the software! I'll move commit signing higher in my list of priorities.
Also, if you see any translation problems do let me know!

**Comment by OuOich** [comment]
Thank you for your reply! It's great to hear that you're willing to address this issue!

I haven't encountered any translation problems in my current usage; they are mostly correct. If I find any issues in the future, I'll open another issue to remind you.

Finally, thank you for developing such amazing software. I look forward to its improvements. Wishing you a happy life!

**Comment by MikeJerred** [comment]
This feature has been added to v1.9.0
