### ISSUE TITLE
Unable to start in Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by Aleksandr-ru** [LogicOverSnacks/glint-release#7]
**Describe the bug**
Glint-1.2.1.AppImage won't start in Ubuntu 18.04

**To Reproduce**
1. Go to console and start `./Glint-1.2.1.AppImage`
2. See error
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found
```

**Expected behavior**
Normal application startup

**Screenshots**
![image](https://user-images.githubusercontent.com/15122148/229467093-e41c2b90-08cd-4434-aef6-62779c361146.png)

**System Information (please complete the following information):**
 - OS: Ubuntu 18.04 LTS (elementary OS 5.1.7 Hera)
 - Glint version 1.2.1

**Additional context**
Ubuntu 18 has only GLIBCXX_3.4.25 
```
strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep -i glibcxx
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_3.4.23
GLIBCXX_3.4.24
GLIBCXX_3.4.25
GLIBCXX_DEBUG_MESSAGE_LENGTH
```
The issue looks similar to https://github.com/LedgerHQ/ledger-live-desktop/issues/4016
but upgrading to gcc-9 from test builds is not a good idea.

PS: version from snap works correctly

**Comment by MikeJerred** [comment]
I have built an AppImage version with `libstdc++` included, which should hopefully fix this issue. Unfortunately, the GitHub Actions Ubuntu 18.04 runner has an updated gcc version so I cannot test there. If possible could you download [this](https://drive.google.com/file/d/188A3J_29DE7KRd6RRJRxU-kd4PuGprh3/view?usp=share_link) AppImage and see if it works?

**Comment by Aleksandr-ru** [comment]
Tried app by your link and got new error
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.mount_Glint-5rpFao/resources/app/dist/native_modules/build/Release/nodegit.node)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1226:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:1822)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at f._load (node:electron/js2c/asar_bundle:2:13328)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at 27241 (/tmp/.mount_Glint-5rpFao/resources/app/dist/main.js:2:258221)
    at r (/tmp/.mount_Glint-5rpFao/resources/app/dist/main.js:14:1258656)
```

Now its about GLIBC_2.28, looks like 2.18 is latest
```
strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep -i glibc_
GLIBC_2.2.5
GLIBC_2.3
GLIBC_2.14
GLIBC_2.4
GLIBC_2.18
GLIBC_2.16
GLIBC_2.3.4
GLIBC_2.17
GLIBC_2.3.2
```

**Comment by MikeJerred** [comment]
Thanks for checking that. Unfortunately, fixing this would require manual building of dependencies since the GitHub Actions ubuntu-18.04 runner is actually deprecated now. Even if I were to do this, it would break on the next upgrade to Electron since that requires node 18.

Basically, Ubuntu 18.04 is reaching the end of life (30th April 2023), so I think the best thing here is to recommend upgrading Ubuntu or using the snap package. I have added a troubleshooting tip to that effect on the website: https://glint.info/docs/troubleshooting
