### ISSUE TITLE
Option to change font size and/or UI scale

### ISSUE THREAD

**Issue by lfom** [LogicOverSnacks/glint-release#9]
**Is your feature request related to a problem? Please describe.**
Glint UI is great, but it does not work well with "small" screen resolutions like 1280x800 or 1366x768. An option to scale the font probably will help.

**Describe the solution you'd like**
Add a feature in Settings to change the font size used in the app and/or scale the whole UI.

**Describe alternatives you've considered**
Not much can be done in this case, I am afraid.

**Additional context**
None, but thank you a lot for providing a nice git GUI that is free even for private repos! Keep up the good work!

Regards

**Comment by MikeJerred** [comment]
Thanks for this! I will look at adding an option to change the font size.

**Comment by MikeJerred** [comment]
Comparison of a reduced font-size at 1280x800:
![image](https://github.com/LogicOverSnacks/glint-release/assets/17481425/edf536dd-9389-4420-8634-af1dead43e53)

Compared to normal:
![image](https://github.com/LogicOverSnacks/glint-release/assets/17481425/9c773c7f-9159-4116-9bb0-d89cee9f4be0)

I think this makes the app a bit less clunky so I can certainly add a setting for it.
Did you have any specific usability concerns at small screen sizes?
For example: I noticed that when viewing a diff, the find box can take up a lot of the width and push the close button off screen.

**Comment by lfom** [comment]
> I think this makes the app a bit less clunky so I can certainly add a setting for it. Did you have any specific usability concerns at small screen sizes? For example: I noticed that when viewing a diff, the find box can take up a lot of the width and push the close button off screen.

Hey, it looks great! Yeah, besides an overall big text in some boxes (like in the commit one), here the close button is completely hidden when viewing a diff, so I must hide the left panel in order to close it. Nothing else like this from the top of my head (I was using Glint recently on a FullHD display).

**Comment by MikeJerred** [comment]
Fixed in [v1.8.0](https://github.com/LogicOverSnacks/glint-release/releases/tag/v1.8.0)

**Comment by lfom** [comment]
@MikeJerred Sorry for the late reply, but today I was able to use v1.8.o on my convertible, it has a 11" screen. I think most displays with lower resolution also are small, like mine. 

I think the commit lines are a bit tiny now, while the commit message (top right box) still look somewhat big. Also in the app main page, the Recently Opened items are hard to read, same as commit lines. 

Please refer to to attached screen shots.

Cheers

![Screenshot from 2023-11-01 20-19-02](https://github.com/LogicOverSnacks/glint-release/assets/15659999/fd12eb1d-fdb4-4104-8f9e-2a0a70448536)
![Screenshot from 2023-11-01 20-19-22](https://github.com/LogicOverSnacks/glint-release/assets/15659999/0c2bd126-5cea-4be7-b5f8-9017049e1dfa)

**Comment by MikeJerred** [comment]
I think the solution is to have the commit message use a smaller font after the first line

**Comment by MikeJerred** [comment]
Fixed in [v1.8.1](https://github.com/LogicOverSnacks/glint-release/releases/tag/v1.8.1)
